import type { GeneratedClosedRouteV3 } from "@/lib/contracts/routes";

type ExportRoute = Pick<GeneratedClosedRouteV3, "geometry" | "startAccessPoint" | "warnings" | "source">;

function xmlText(value: string): string {
  // XML 1.0 excludes most control characters and unpaired UTF-16 surrogates.
  return Array.from(value, (character) => {
    const point = character.codePointAt(0)!;
    const valid = point === 0x9 || point === 0xa || point === 0xd
      || (point >= 0x20 && point <= 0xd7ff)
      || (point >= 0xe000 && point <= 0xfffd)
      || (point >= 0x10000 && point <= 0x10ffff);
    if (!valid) return "�";
    switch (character) {
      case "&": return "&amp;";
      case "<": return "&lt;";
      case ">": return "&gt;";
      case '"': return "&quot;";
      case "'": return "&apos;";
      default: return character;
    }
  }).join("");
}

/** Export the full traveled path, including retraced sections, as a GPX 1.1 track. */
export function routeGpx(route: ExportRoute, name: string): string {
  const [startLon, startLat] = route.geometry.coordinates[0]
    ?? [route.startAccessPoint.lon, route.startAccessPoint.lat];
  const description = [
    "Generated by Alpine Loop.",
    `Sources: ${route.source.sourceIds.join(", ")}`,
    `Source freshness: ${route.source.freshness}`,
    `Source confidence: ${route.source.confidence}`,
    ...route.warnings.map((warning) => `Warning: ${warning}`),
  ].join("\n");
  // Elevation-profile samples are not paired with geometry coordinates.
  const points = route.geometry.coordinates.map(([lon, lat]) =>
    `      <trkpt lat="${lat}" lon="${lon}" />`,
  );
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<gpx version="1.1" creator="Alpine Loop" xmlns="http://www.topografix.com/GPX/1/1">',
    `  <wpt lat="${startLat}" lon="${startLon}">`,
    `    <name>${xmlText(route.startAccessPoint.name)}</name>`,
    "  </wpt>",
    "  <trk>",
    `    <name>${xmlText(name)}</name>`,
    `    <desc>${xmlText(description)}</desc>`,
    "    <trkseg>",
    ...points,
    "    </trkseg>",
    "  </trk>",
    "</gpx>",
    "",
  ].join("\n");
}

export function routeGpxFilename(name: string): string {
  const stem = name.normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
    .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")
    .slice(0, 100).replace(/-+$/g, "");
  // A prefix also avoids platform-reserved file names such as CON and NUL.
  return `alpine-loop-${stem || "route"}.gpx`;
}
